### PR TITLE
Apply bounds after performing row bound tightening

### PR DESCRIPTION
**Pull request by anwu1219**
Currently in solve() after we perform **explicitBasisBoundTightening()**  we do not apply the updated bounds to _tableau until we have called  **_tableau->allBoundsValid()"" and **performSymbolicBoundTightening()**. This could result in non-trivial delay in concluding UNSAT. This PR fixes this issue.
Runtime comparison pending...

### CODE REVIEW

**Comment by guykatzz** [comment]
The change LGTM. Lets see what the performance gain is.

**Comment by guykatzz** [comment]
Hi Andrew,
Did the experiments finish running for this PR? Was there an improvement?

**Comment by anwu1219** [comment]
> Hi Andrew,
> Did the experiments finish running for this PR? Was there an improvement?

Hi Guy, on the commonly solved instances, there seem to be 10% runtime improvement. However, occasionally Marabou throws Error with the new changes, so I'm looking into that.

**Comment by anwu1219** [comment]
On 40 acas, 40 mnist, 60 taxinet benchmarks, the two runs solve the same number of queries within 1 hour.
This branch: 29663 sec
Master: 31447 sec

**Pull request merged**
